"""PostgreSQL 业务域仓储（方案 A：多引擎分工）。
架构定位（与 SQLite 检索库并存，方法同名同签名，由 HybridStore 按域路由）：
- **PostgreSQL**：业务事务域 —— 用户/会话/订单/运营/埋点/特征/模型治理/评测/审计/kv，
  承担事务性写入与多实例一致性；
- **SQLite（FTS5）**：检索索引库 —— 图书/章节/知识块全文索引（中文分词友好），
  类比业界 "关系库 + 检索引擎(ES)" 双层组合。

安全约定：所有 SQL 均为方法体内联的完整字面量（无任何变量透传/拼接/变换），
值一律 %s 参数化绑定。
"""
import threading
import time
from contextlib import contextmanager

import psycopg

from .config import settings


def now_iso() -> str:
    from datetime import datetime

    return datetime.now().isoformat(timespec="seconds")


def dumps(obj) -> str:
    import json

    return json.dumps(obj, ensure_ascii=False, default=str)


def loads(s, default=None):
    import json

    if not s:
        return default
    try:
        return json.loads(s)
    except (TypeError, ValueError):
        return default


class PgRepository:
    """PostgreSQL 业务域仓储（与 Database 同名方法，由 HybridStore 路由委托）。"""

    def __init__(self, dsn: str):
        if not dsn:
            raise ValueError("PG_DSN 未配置")
        self.dsn = dsn
        self._local = threading.local()

    def init_schema(self) -> None:
        with self._tx() as c:
            c.execute("CREATE TABLE IF NOT EXISTS kv(key TEXT PRIMARY KEY, value TEXT)")
            c.execute("CREATE TABLE IF NOT EXISTS users(id BIGINT GENERATED BY DEFAULT"
                      " AS IDENTITY PRIMARY KEY, username TEXT UNIQUE NOT NULL,"
                      " password_hash TEXT NOT NULL, role TEXT DEFAULT 'user',"
                      " nickname TEXT, created_at TEXT)")
            c.execute("CREATE TABLE IF NOT EXISTS user_profiles(user_id BIGINT PRIMARY"
                      " KEY, pref_categories TEXT, pref_tags TEXT, recent_books TEXT,"
                      " summary TEXT, updated_at TEXT)")
            c.execute("CREATE TABLE IF NOT EXISTS chat_sessions(id TEXT PRIMARY KEY,"
                      " user_id BIGINT, title TEXT, created_at TEXT, updated_at TEXT)")
            c.execute("CREATE TABLE IF NOT EXISTS chat_messages(id BIGINT GENERATED BY"
                      " DEFAULT AS IDENTITY PRIMARY KEY, session_id TEXT, role TEXT,"
                      " content TEXT, meta TEXT, created_at TEXT)")
            c.execute("CREATE TABLE IF NOT EXISTS memory_short(session_id TEXT, key TEXT,"
                      " value TEXT, expires_at DOUBLE PRECISION,"
                      " PRIMARY KEY(session_id, key))")
            c.execute("CREATE TABLE IF NOT EXISTS memory_long(user_id BIGINT, key TEXT,"
                      " value TEXT, weight DOUBLE PRECISION DEFAULT 1.0, updated_at TEXT,"
                      " PRIMARY KEY(user_id, key))")
            c.execute("CREATE TABLE IF NOT EXISTS user_library(user_id BIGINT,"
                      " book_id TEXT, action TEXT, created_at TEXT,"
                      " PRIMARY KEY(user_id, book_id))")
            c.execute("CREATE TABLE IF NOT EXISTS auth_tokens(token_hash TEXT PRIMARY"
                      " KEY, user_id BIGINT, kind TEXT, expires_at DOUBLE PRECISION,"
                      " revoked INT DEFAULT 0, created_at TEXT)")
            c.execute("CREATE INDEX IF NOT EXISTS idx_auth_tokens_user"
                      " ON auth_tokens(user_id)")
            c.execute("CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,"
                      " user_id BIGINT, book_id TEXT, qty INT DEFAULT 1,"
                      " price DOUBLE PRECISION DEFAULT 0, status TEXT DEFAULT 'pending',"
                      " confirm_token TEXT, token_expires DOUBLE PRECISION,"
                      " risk_flags TEXT, created_at TEXT, paid_at TEXT)")
            c.execute("CREATE TABLE IF NOT EXISTS ops_strategies(key TEXT PRIMARY KEY,"
                      " value TEXT, updated_by TEXT, updated_at TEXT)")
            c.execute("CREATE TABLE IF NOT EXISTS ops_campaigns(id BIGINT GENERATED BY"
                      " DEFAULT AS IDENTITY PRIMARY KEY, name TEXT, slot TEXT,"
                      " book_ids TEXT, weight DOUBLE PRECISION DEFAULT 1.0,"
                      " start_at TEXT, end_at TEXT, enabled INT DEFAULT 1,"
                      " created_at TEXT)")
            c.execute("CREATE TABLE IF NOT EXISTS ops_priority_books(book_id TEXT,"
                      " slot TEXT, weight DOUBLE PRECISION DEFAULT 1.0, reason TEXT,"
                      " PRIMARY KEY(slot, book_id))")
            c.execute("CREATE TABLE IF NOT EXISTS ops_experiments(id BIGINT GENERATED BY"
                      " DEFAULT AS IDENTITY PRIMARY KEY, name TEXT UNIQUE,"
                      " description TEXT, traffic_pct DOUBLE PRECISION DEFAULT 100,"
                      " variants TEXT, status TEXT DEFAULT 'running', winner TEXT,"
                      " created_at TEXT)")
            c.execute("CREATE TABLE IF NOT EXISTS ops_assignments(exp_id BIGINT,"
                      " user_id BIGINT, variant TEXT, assigned_at TEXT,"
                      " PRIMARY KEY(exp_id, user_id))")
            c.execute("CREATE TABLE IF NOT EXISTS ops_prompts(id BIGINT GENERATED BY"
                      " DEFAULT AS IDENTITY PRIMARY KEY, name TEXT, version INT"
                      " DEFAULT 1, template TEXT, updated_by TEXT, updated_at TEXT)")
            c.execute("CREATE INDEX IF NOT EXISTS idx_ops_prompts_name"
                      " ON ops_prompts(name, version)")
            c.execute("CREATE TABLE IF NOT EXISTS event_queue(id BIGINT GENERATED BY"
                      " DEFAULT AS IDENTITY PRIMARY KEY, payload TEXT,"
                      " status TEXT DEFAULT 'new', claimed_at DOUBLE PRECISION,"
                      " created_at TEXT, consumed_at TEXT)")
            c.execute("CREATE TABLE IF NOT EXISTS events(id BIGINT GENERATED BY DEFAULT"
                      " AS IDENTITY PRIMARY KEY, ts TEXT, user_id BIGINT,"
                      " session_id TEXT, event_type TEXT, book_id TEXT, query TEXT,"
                      " props TEXT)")
            c.execute("CREATE INDEX IF NOT EXISTS idx_events_type_ts"
                      " ON events(event_type, ts)")
            c.execute("CREATE INDEX IF NOT EXISTS idx_events_user ON events(user_id)")
            c.execute("CREATE TABLE IF NOT EXISTS features_user(user_id BIGINT,"
                      " feature_key TEXT, value DOUBLE PRECISION DEFAULT 0,"
                      " value_json TEXT, updated_at TEXT,"
                      " PRIMARY KEY(user_id, feature_key))")
            c.execute("CREATE TABLE IF NOT EXISTS features_book(book_id TEXT,"
                      " feature_key TEXT, value DOUBLE PRECISION DEFAULT 0,"
                      " updated_at TEXT, PRIMARY KEY(book_id, feature_key))")
            c.execute("CREATE TABLE IF NOT EXISTS rec_models(id BIGINT GENERATED BY"
                      " DEFAULT AS IDENTITY PRIMARY KEY, kind TEXT, version TEXT,"
                      " artifact TEXT, metrics TEXT, trained_at TEXT)")
            c.execute("CREATE TABLE IF NOT EXISTS rec_candidates(user_id BIGINT,"
                      " model_version TEXT, book_ids TEXT, scores TEXT, updated_at TEXT,"
                      " PRIMARY KEY(user_id, model_version))")
            c.execute("CREATE TABLE IF NOT EXISTS mh_calls(id BIGINT GENERATED BY"
                      " DEFAULT AS IDENTITY PRIMARY KEY, ts TEXT, trace_id TEXT,"
                      " user_id BIGINT, service TEXT, provider TEXT, model TEXT,"
                      " tier TEXT, prompt_tokens INT DEFAULT 0,"
                      " completion_tokens INT DEFAULT 0,"
                      " cost DOUBLE PRECISION DEFAULT 0,"
                      " latency_ms DOUBLE PRECISION DEFAULT 0, status TEXT, error TEXT)")
            c.execute("CREATE TABLE IF NOT EXISTS mh_quota_daily(day TEXT, user_id BIGINT,"
                      " calls INT DEFAULT 0, tokens INT DEFAULT 0,"
                      " cost DOUBLE PRECISION DEFAULT 0, PRIMARY KEY(day, user_id))")
            c.execute("CREATE TABLE IF NOT EXISTS eval_cases(id BIGINT GENERATED BY"
                      " DEFAULT AS IDENTITY PRIMARY KEY, suite TEXT, question TEXT,"
                      " gold_answer TEXT, gold_citations TEXT, expect_refusal INT"
                      " DEFAULT 0, tags TEXT)")
            c.execute("CREATE TABLE IF NOT EXISTS eval_runs(id BIGINT GENERATED BY"
                      " DEFAULT AS IDENTITY PRIMARY KEY, ts TEXT, suite TEXT, total INT,"
                      " passed INT, metrics TEXT, gates TEXT, gate_passed INT,"
                      " details TEXT)")
            c.execute("CREATE TABLE IF NOT EXISTS audit_logs(id BIGINT GENERATED BY"
                      " DEFAULT AS IDENTITY PRIMARY KEY, ts TEXT, user_id BIGINT,"
                      " trace_id TEXT, action TEXT, tool TEXT, params TEXT,"
                      " decision TEXT, reason TEXT)")
            c.execute("CREATE TABLE IF NOT EXISTS injection_hits(id BIGINT GENERATED BY"
                      " DEFAULT AS IDENTITY PRIMARY KEY, ts TEXT, user_id BIGINT,"
                      " source TEXT, snippet TEXT, patterns TEXT,"
                      " score DOUBLE PRECISION, blocked INT)")

    def _conn(self):
        conn = getattr(self._local, "conn", None)
        if conn is None:
            from psycopg.rows import dict_row

            conn = psycopg.connect(self.dsn, row_factory=dict_row)
            self._local.conn = conn
        return conn

    @contextmanager
    def _tx(self):
        """事务上下文（psycopg3 的 with connect 会关闭连接，故用手动提交/回滚）。"""
        conn = self._conn()
        try:
            yield conn
            conn.commit()
        except Exception:
            conn.rollback()
            raise

    # ---------- kv ----------
    def kv_get(self, key: str, default=None):
        with self._tx() as c:
            rows = [dict(r) for r in c.execute(
                "SELECT value FROM kv WHERE key=%s", (key,)).fetchall()]
        return rows[0]["value"] if rows else default

    def kv_set(self, key: str, value: str) -> None:
        with self._tx() as c:
            c.execute(
                "INSERT INTO kv(key, value) VALUES(%s,%s) "
                "ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value",
                (key, value),
            )

    # ---------- 用户域 ----------
    def create_user(self, username, password_hash, role, nickname) -> int:
        with self._tx() as c:
            cur = c.execute(
                "INSERT INTO users(username, password_hash, role, nickname, created_at)"
                " VALUES(%s,%s,%s,%s,%s) RETURNING id",
                (username, password_hash, role, nickname, now_iso()),
            )
            return cur.fetchone()["id"]

    def get_user_by_username(self, username):
        with self._tx() as c:
            rows = [dict(r) for r in c.execute(
                "SELECT * FROM users WHERE username=%s", (username,)).fetchall()]
        return rows[0] if rows else None

    def get_user(self, user_id):
        with self._tx() as c:
            rows = [dict(r) for r in c.execute(
                "SELECT * FROM users WHERE id=%s", (user_id,)).fetchall()]
        return rows[0] if rows else None

    def list_users(self):
        with self._tx() as c:
            return [dict(r) for r in c.execute(
                "SELECT id, username, role, nickname, created_at FROM users ORDER BY id"
            ).fetchall()]

    def get_profile(self, user_id):
        with self._tx() as c:
            rows = [dict(r) for r in c.execute(
                "SELECT * FROM user_profiles WHERE user_id=%s", (user_id,)).fetchall()]
        return rows[0] if rows else None

    def upsert_profile(self, user_id, pref_categories, pref_tags, recent_books,
                       summary) -> None:
        with self._tx() as c:
            c.execute(
                "INSERT INTO user_profiles(user_id, pref_categories, pref_tags,"
                " recent_books, summary, updated_at) VALUES(%s,%s,%s,%s,%s,%s)"
                " ON CONFLICT(user_id) DO UPDATE SET"
                " pref_categories=EXCLUDED.pref_categories,"
                " pref_tags=EXCLUDED.pref_tags,"
                " recent_books=EXCLUDED.recent_books, summary=EXCLUDED.summary,"
                " updated_at=EXCLUDED.updated_at",
                (user_id, pref_categories, pref_tags, recent_books, summary, now_iso()),
            )

    # ---------- 会话与消息 ----------
    def create_session(self, session_id, user_id, title) -> None:
        with self._tx() as c:
            c.execute(
                "INSERT INTO chat_sessions(id, user_id, title, created_at, updated_at)"
                " VALUES(%s,%s,%s,%s,%s)",
                (session_id, user_id, title, now_iso(), now_iso()),
            )

    def touch_session(self, session_id, title="") -> None:
        with self._tx() as c:
            if title:
                c.execute(
                    "UPDATE chat_sessions SET updated_at=%s,"
                    " title=CASE WHEN title='' THEN %s ELSE title END WHERE id=%s",
                    (now_iso(), title[:40], session_id),
                )
            else:
                c.execute(
                    "UPDATE chat_sessions SET updated_at=%s WHERE id=%s",
                    (now_iso(), session_id),
                )

    def get_session(self, session_id):
        with self._tx() as c:
            rows = [dict(r) for r in c.execute(
                "SELECT * FROM chat_sessions WHERE id=%s", (session_id,)).fetchall()]
        return rows[0] if rows else None

    def list_sessions(self, user_id):
        with self._tx() as c:
            return [dict(r) for r in c.execute(
                "SELECT * FROM chat_sessions WHERE user_id=%s"
                " ORDER BY updated_at DESC LIMIT 100", (user_id,)).fetchall()]

    def delete_session(self, session_id) -> None:
        with self._tx() as c:
            c.execute("DELETE FROM chat_messages WHERE session_id=%s", (session_id,))
            c.execute("DELETE FROM memory_short WHERE session_id=%s", (session_id,))
            c.execute("DELETE FROM chat_sessions WHERE id=%s", (session_id,))

    def add_message(self, session_id, role, content, meta) -> int:
        with self._tx() as c:
            cur = c.execute(
                "INSERT INTO chat_messages(session_id, role, content, meta, created_at)"
                " VALUES(%s,%s,%s,%s,%s) RETURNING id",
                (session_id, role, content, meta, now_iso()),
            )
            return cur.fetchone()["id"]

    def get_messages(self, session_id, limit=100):
        with self._tx() as c:
            rows = [dict(r) for r in c.execute(
                "SELECT * FROM chat_messages WHERE session_id=%s"
                " ORDER BY id DESC LIMIT %s", (session_id, limit)).fetchall()]
        return list(reversed(rows))

    # ---------- 记忆 ----------
    def mem_short_get(self, session_id, key):
        with self._tx() as c:
            rows = [dict(r) for r in c.execute(
                "SELECT value, expires_at FROM memory_short"
                " WHERE session_id=%s AND key=%s", (session_id, key)).fetchall()]
        if not rows:
            return None
        if rows[0]["expires_at"] and rows[0]["expires_at"] < time.time():
            return None
        return rows[0]["value"]

    def mem_short_set(self, session_id, key, value, expires_at) -> None:
        with self._tx() as c:
            c.execute(
                "INSERT INTO memory_short(session_id, key, value, expires_at)"
                " VALUES(%s,%s,%s,%s)"
                " ON CONFLICT(session_id, key) DO UPDATE SET value=EXCLUDED.value,"
                " expires_at=EXCLUDED.expires_at",
                (session_id, key, value, expires_at),
            )

    def mem_long_get(self, user_id, key):
        with self._tx() as c:
            rows = [dict(r) for r in c.execute(
                "SELECT value FROM memory_long WHERE user_id=%s AND key=%s",
                (user_id, key)).fetchall()]
        return rows[0]["value"] if rows else None

    def mem_long_set(self, user_id, key, value, weight=1.0) -> None:
        with self._tx() as c:
            c.execute(
                "INSERT INTO memory_long(user_id, key, value, weight, updated_at)"
                " VALUES(%s,%s,%s,%s,%s)"
                " ON CONFLICT(user_id, key) DO UPDATE SET value=EXCLUDED.value,"
                " weight=EXCLUDED.weight, updated_at=EXCLUDED.updated_at",
                (user_id, key, value, weight, now_iso()),
            )

    # ---------- 藏书库 ----------
    def library_upsert(self, user_id, book_id, action) -> None:
        with self._tx() as c:
            c.execute(
                "INSERT INTO user_library(user_id, book_id, action, created_at)"
                " VALUES(%s,%s,%s,%s)"
                " ON CONFLICT(user_id, book_id) DO UPDATE SET action=EXCLUDED.action,"
                " created_at=EXCLUDED.created_at",
                (user_id, book_id, action, now_iso()),
            )

    def library_list(self, user_id, action=""):
        with self._tx() as c:
            if action:
                return [dict(r) for r in c.execute(
                    "SELECT * FROM user_library WHERE user_id=%s AND action=%s"
                    " ORDER BY created_at DESC", (user_id, action)).fetchall()]
            return [dict(r) for r in c.execute(
                "SELECT * FROM user_library WHERE user_id=%s"
                " ORDER BY created_at DESC", (user_id,)).fetchall()]

    # ---------- 刷新令牌 ----------
    def auth_token_save(self, token_hash, user_id, kind, expires_at) -> None:
        with self._tx() as c:
            c.execute(
                "INSERT INTO auth_tokens(token_hash, user_id, kind, expires_at, revoked,"
                " created_at) VALUES(%s,%s,%s,%s,0,%s)"
                " ON CONFLICT(token_hash) DO UPDATE SET revoked=0,"
                " expires_at=EXCLUDED.expires_at",
                (token_hash, user_id, kind, expires_at, now_iso()),
            )

    def auth_token_get_valid(self, token_hash, kind):
        with self._tx() as c:
            rows = [dict(r) for r in c.execute(
                "SELECT * FROM auth_tokens WHERE token_hash=%s AND kind=%s"
                " AND revoked=0 AND expires_at > %s LIMIT 1",
                (token_hash, kind, time.time())).fetchall()]
        return rows[0] if rows else None

    def auth_token_revoke(self, token_hash) -> None:
        with self._tx() as c:
            c.execute(
                "UPDATE auth_tokens SET revoked=1 WHERE token_hash=%s", (token_hash,)
            )

    def auth_token_revoke_all(self, user_id, kind) -> None:
        with self._tx() as c:
            c.execute(
                "UPDATE auth_tokens SET revoked=1 WHERE user_id=%s AND kind=%s",
                (user_id, kind),
            )

    # ---------- 订单域 ----------
    def create_order(self, order_id, user_id, book_id, qty, price, confirm_token,
                     token_expires, risk_flags) -> None:
        with self._tx() as c:
            c.execute(
                "INSERT INTO orders(id, user_id, book_id, qty, price, status,"
                " confirm_token, token_expires, risk_flags, created_at)"
                " VALUES(%s,%s,%s,%s,%s,'pending',%s,%s,%s,%s)",
                (order_id, user_id, book_id, qty, price, confirm_token, token_expires,
                 risk_flags, now_iso()),
            )

    def get_order(self, order_id):
        with self._tx() as c:
            rows = [dict(r) for r in c.execute(
                "SELECT * FROM orders WHERE id=%s", (order_id,)).fetchall()]
        return rows[0] if rows else None

    def set_order_status(self, order_id, status, paid_at="") -> None:
        with self._tx() as c:
            c.execute(
                "UPDATE orders SET status=%s,"
                " paid_at=CASE WHEN %s='' THEN paid_at ELSE %s END WHERE id=%s",
                (status, paid_at, paid_at, order_id),
            )

    def count_recent_orders(self, user_id, since_ts):
        with self._tx() as c:
            rows = [dict(r) for r in c.execute(
                "SELECT COUNT(*) AS n FROM orders WHERE user_id=%s AND created_at>=%s",
                (user_id, since_ts)).fetchall()]
        return rows[0]["n"] if rows else 0

    # ---------- 运营域 ----------
    def strategy_get(self, key):
        with self._tx() as c:
            rows = [dict(r) for r in c.execute(
                "SELECT value FROM ops_strategies WHERE key=%s", (key,)).fetchall()]
        return rows[0]["value"] if rows else None

    def strategy_set(self, key, value, by) -> None:
        with self._tx() as c:
            c.execute(
                "INSERT INTO ops_strategies(key, value, updated_by, updated_at)"
                " VALUES(%s,%s,%s,%s)"
                " ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,"
                " updated_by=EXCLUDED.updated_by, updated_at=EXCLUDED.updated_at",
                (key, value, by, now_iso()),
            )

    def strategy_all(self):
        with self._tx() as c:
            return [dict(r) for r in c.execute(
                "SELECT * FROM ops_strategies ORDER BY key").fetchall()]

    def campaign_create(self, name, slot, book_ids, weight, start_at, end_at,
                        enabled) -> int:
        with self._tx() as c:
            cur = c.execute(
                "INSERT INTO ops_campaigns(name, slot, book_ids, weight, start_at,"
                " end_at, enabled, created_at) VALUES(%s,%s,%s,%s,%s,%s,%s,%s)"
                " RETURNING id",
                (name, slot, book_ids, weight, start_at, end_at, enabled, now_iso()),
            )
            return cur.fetchone()["id"]

    def campaign_update(self, campaign_id, enabled) -> None:
        with self._tx() as c:
            c.execute(
                "UPDATE ops_campaigns SET enabled=%s WHERE id=%s", (enabled, campaign_id)
            )

    def campaign_delete(self, campaign_id) -> None:
        with self._tx() as c:
            c.execute("DELETE FROM ops_campaigns WHERE id=%s", (campaign_id,))

    def campaign_list(self):
        with self._tx() as c:
            return [dict(r) for r in c.execute(
                "SELECT * FROM ops_campaigns ORDER BY id DESC").fetchall()]

    def campaigns_active(self, now):
        with self._tx() as c:
            return [dict(r) for r in c.execute(
                "SELECT * FROM ops_campaigns WHERE enabled=1"
                " AND (start_at='' OR start_at IS NULL OR start_at<=%s)"
                " AND (end_at='' OR end_at IS NULL OR end_at>=%s)", (now, now)).fetchall()]

    def priority_upsert(self, slot, book_id, weight, reason) -> None:
        with self._tx() as c:
            c.execute(
                "INSERT INTO ops_priority_books(book_id, slot, weight, reason)"
                " VALUES(%s,%s,%s,%s)"
                " ON CONFLICT(slot, book_id) DO UPDATE SET weight=EXCLUDED.weight,"
                " reason=EXCLUDED.reason",
                (book_id, slot, weight, reason),
            )

    def priority_list(self, slot=""):
        with self._tx() as c:
            if slot:
                return [dict(r) for r in c.execute(
                    "SELECT * FROM ops_priority_books WHERE slot=%s"
                    " ORDER BY weight DESC", (slot,)).fetchall()]
            return [dict(r) for r in c.execute(
                "SELECT * FROM ops_priority_books ORDER BY slot, weight DESC"
            ).fetchall()]

    def priority_delete(self, slot, book_id) -> None:
        with self._tx() as c:
            c.execute(
                "DELETE FROM ops_priority_books WHERE slot=%s AND book_id=%s",
                (slot, book_id),
            )

    def exp_create(self, name, description, traffic_pct, variants) -> int:
        with self._tx() as c:
            cur = c.execute(
                "INSERT INTO ops_experiments(name, description, traffic_pct, variants,"
                " created_at) VALUES(%s,%s,%s,%s,%s) RETURNING id",
                (name, description, traffic_pct, variants, now_iso()),
            )
            return cur.fetchone()["id"]

    def exp_list(self):
        with self._tx() as c:
            return [dict(r) for r in c.execute(
                "SELECT * FROM ops_experiments ORDER BY id DESC").fetchall()]

    def exp_get_by_name(self, name):
        with self._tx() as c:
            rows = [dict(r) for r in c.execute(
                "SELECT * FROM ops_experiments WHERE name=%s", (name,)).fetchall()]
        return rows[0] if rows else None

    def exp_get(self, exp_id):
        with self._tx() as c:
            rows = [dict(r) for r in c.execute(
                "SELECT * FROM ops_experiments WHERE id=%s", (exp_id,)).fetchall()]
        return rows[0] if rows else None

    def exp_finish(self, exp_id, status, winner) -> None:
        with self._tx() as c:
            c.execute(
                "UPDATE ops_experiments SET status=%s, winner=%s WHERE id=%s",
                (status, winner, exp_id),
            )

    def exp_assign(self, exp_id, user_id, variant) -> None:
        with self._tx() as c:
            c.execute(
                "INSERT INTO ops_assignments(exp_id, user_id, variant, assigned_at)"
                " VALUES(%s,%s,%s,%s)"
                " ON CONFLICT(exp_id, user_id) DO UPDATE SET variant=EXCLUDED.variant",
                (exp_id, user_id, variant, now_iso()),
            )

    def exp_get_assignment(self, exp_id, user_id):
        with self._tx() as c:
            rows = [dict(r) for r in c.execute(
                "SELECT variant FROM ops_assignments WHERE exp_id=%s AND user_id=%s",
                (exp_id, user_id)).fetchall()]
        return rows[0]["variant"] if rows else None

    # ---------- Prompt 版本（P1-5）----------
    def prompt_latest(self, name):
        with self._tx() as c:
            rows = [dict(r) for r in c.execute(
                "SELECT * FROM ops_prompts WHERE name=%s"
                " ORDER BY version DESC LIMIT 1", (name,)).fetchall()]
        return rows[0] if rows else None

    def prompt_save(self, name, version, template, by) -> None:
        with self._tx() as c:
            c.execute(
                "INSERT INTO ops_prompts(name, version, template, updated_by,"
                " updated_at) VALUES(%s,%s,%s,%s,%s)",
                (name, version, template, by, now_iso()),
            )

    # ---------- 埋点与离线域 ----------
    def event_enqueue(self, payload) -> int:
        with self._tx() as c:
            cur = c.execute(
                "INSERT INTO event_queue(payload, status, created_at)"
                " VALUES(%s, 'new', %s) RETURNING id",
                (payload, now_iso()),
            )
            return cur.fetchone()["id"]

    def event_claim_batch(self, limit=200, lease_seconds=300.0):
        deadline = time.time() - lease_seconds
        with self._tx() as c:
            cur = c.execute(
                "UPDATE event_queue SET status='processing', claimed_at=%s"
                " WHERE id IN (SELECT id FROM event_queue"
                " WHERE status='new'"
                " OR (status='processing' AND (claimed_at IS NULL OR claimed_at < %s))"
                " ORDER BY id LIMIT %s)"
                " RETURNING id, payload",
                (time.time(), deadline, limit),
            )
            return [dict(r) for r in cur.fetchall()]

    def event_mark_done(self, ids) -> None:
        with self._tx() as c:
            for i in ids:
                c.execute(
                    "UPDATE event_queue SET status='done', consumed_at=%s WHERE id=%s",
                    (now_iso(), i),
                )

    def event_release(self, ids) -> None:
        with self._tx() as c:
            for i in ids:
                c.execute(
                    "UPDATE event_queue SET status='new', claimed_at=NULL WHERE id=%s",
                    (i,),
                )

    def event_insert(self, ts, user_id, session_id, event_type, book_id, query,
                     props) -> int:
        with self._tx() as c:
            cur = c.execute(
                "INSERT INTO events(ts, user_id, session_id, event_type, book_id,"
                " query, props) VALUES(%s,%s,%s,%s,%s,%s,%s) RETURNING id",
                (ts, user_id, session_id, event_type, book_id, query, props),
            )
            return cur.fetchone()["id"]

    def events_query(self, event_type="", since="", user_id=None, limit=1000):
        with self._tx() as c:
            if event_type and since and user_id is not None:
                return [dict(r) for r in c.execute(
                    "SELECT * FROM events WHERE event_type=%s AND ts>=%s"
                    " AND user_id=%s ORDER BY id LIMIT %s",
                    (event_type, since, user_id, limit)).fetchall()]
            if event_type and since:
                return [dict(r) for r in c.execute(
                    "SELECT * FROM events WHERE event_type=%s AND ts>=%s"
                    " ORDER BY id LIMIT %s", (event_type, since, limit)).fetchall()]
            if since:
                return [dict(r) for r in c.execute(
                    "SELECT * FROM events WHERE ts>=%s ORDER BY id LIMIT %s",
                    (since, limit)).fetchall()]
            return [dict(r) for r in c.execute(
                "SELECT * FROM events ORDER BY id DESC LIMIT %s", (limit,)).fetchall()]

    def events_count(self, event_type, since=""):
        with self._tx() as c:
            if since:
                rows = [dict(r) for r in c.execute(
                    "SELECT COUNT(*) AS n FROM events WHERE event_type=%s AND ts>=%s",
                    (event_type, since)).fetchall()]
            else:
                rows = [dict(r) for r in c.execute(
                    "SELECT COUNT(*) AS n FROM events WHERE event_type=%s",
                    (event_type,)).fetchall()]
        return rows[0]["n"] if rows else 0

    def feature_user_upsert(self, user_id, key, value, value_json="") -> None:
        with self._tx() as c:
            c.execute(
                "INSERT INTO features_user(user_id, feature_key, value, value_json,"
                " updated_at) VALUES(%s,%s,%s,%s,%s)"
                " ON CONFLICT(user_id, feature_key) DO UPDATE SET"
                " value=EXCLUDED.value, value_json=EXCLUDED.value_json,"
                " updated_at=EXCLUDED.updated_at",
                (user_id, key, value, value_json, now_iso()),
            )

    def feature_user_map(self, user_id):
        with self._tx() as c:
            rows = [dict(r) for r in c.execute(
                "SELECT feature_key, value, value_json FROM features_user"
                " WHERE user_id=%s", (user_id,)).fetchall()]
        return {r["feature_key"]: (r["value"], loads(r["value_json"])) for r in rows}

    def feature_book_upsert(self, book_id, key, value) -> None:
        with self._tx() as c:
            c.execute(
                "INSERT INTO features_book(book_id, feature_key, value, updated_at)"
                " VALUES(%s,%s,%s,%s)"
                " ON CONFLICT(book_id, feature_key) DO UPDATE SET"
                " value=EXCLUDED.value, updated_at=EXCLUDED.updated_at",
                (book_id, key, value, now_iso()),
            )

    def feature_book_map(self):
        with self._tx() as c:
            rows = [dict(r) for r in c.execute(
                "SELECT book_id, feature_key, value FROM features_book").fetchall()]
        out = {}
        for r in rows:
            out.setdefault(r["book_id"], {})[r["feature_key"]] = r["value"]
        return out

    def rec_model_save(self, kind, version, artifact, metrics_json) -> None:
        with self._tx() as c:
            c.execute(
                "INSERT INTO rec_models(kind, version, artifact, metrics, trained_at)"
                " VALUES(%s,%s,%s,%s,%s)",
                (kind, version, artifact, metrics_json, now_iso()),
            )

    def rec_model_latest(self, kind):
        with self._tx() as c:
            rows = [dict(r) for r in c.execute(
                "SELECT * FROM rec_models WHERE kind=%s ORDER BY id DESC LIMIT 1",
                (kind,)).fetchall()]
        return rows[0] if rows else None

    def rec_candidates_save(self, user_id, version, book_ids, scores) -> None:
        with self._tx() as c:
            c.execute(
                "INSERT INTO rec_candidates(user_id, model_version, book_ids, scores,"
                " updated_at) VALUES(%s,%s,%s,%s,%s)"
                " ON CONFLICT(user_id, model_version) DO UPDATE SET"
                " book_ids=EXCLUDED.book_ids, scores=EXCLUDED.scores,"
                " updated_at=EXCLUDED.updated_at",
                (user_id, version, book_ids, scores, now_iso()),
            )

    def rec_candidates_get(self, user_id, version):
        with self._tx() as c:
            rows = [dict(r) for r in c.execute(
                "SELECT * FROM rec_candidates WHERE user_id=%s AND model_version=%s",
                (user_id, version)).fetchall()]
        return rows[0] if rows else None

    # ---------- 模型治理域 ----------
    def mh_call_log(self, ts, trace_id, user_id, service, provider, model, tier,
                    prompt_tokens, completion_tokens, cost, latency_ms, status,
                    error) -> None:
        with self._tx() as c:
            c.execute(
                "INSERT INTO mh_calls(ts, trace_id, user_id, service, provider, model,"
                " tier, prompt_tokens, completion_tokens, cost, latency_ms, status,"
                " error) VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)",
                (ts, trace_id, user_id, service, provider, model, tier, prompt_tokens,
                 completion_tokens, cost, latency_ms, status, error),
            )

    def mh_quota_incr(self, day, user_id, calls, tokens, cost) -> None:
        with self._tx() as c:
            c.execute(
                "INSERT INTO mh_quota_daily(day, user_id, calls, tokens, cost)"
                " VALUES(%s,%s,%s,%s,%s)"
                " ON CONFLICT(day, user_id) DO UPDATE SET"
                " calls=mh_quota_daily.calls+%s, tokens=mh_quota_daily.tokens+%s,"
                " cost=mh_quota_daily.cost+%s",
                (day, user_id if user_id is not None else 0, calls, tokens, cost, calls,
                 tokens, cost),
            )

    def mh_quota_get(self, day, user_id):
        with self._tx() as c:
            rows = [dict(r) for r in c.execute(
                "SELECT calls, tokens, cost FROM mh_quota_daily WHERE day=%s"
                " AND user_id=%s",
                (day, user_id if user_id is not None else 0)).fetchall()]
        return rows[0] if rows else None

    def mh_stats_by_model(self, since):
        with self._tx() as c:
            return [dict(r) for r in c.execute(
                "SELECT service, provider, model, COUNT(*) AS calls,"
                " SUM(prompt_tokens) AS pt, SUM(completion_tokens) AS ct,"
                " SUM(cost) AS cost, AVG(latency_ms) AS avg_ms"
                " FROM mh_calls WHERE ts>=%s GROUP BY service, provider, model"
                " ORDER BY calls DESC", (since,)).fetchall()]

    def mh_recent_calls(self, limit=100):
        with self._tx() as c:
            return [dict(r) for r in c.execute(
                "SELECT * FROM mh_calls ORDER BY id DESC LIMIT %s", (limit,)).fetchall()]

    # ---------- 评测域 ----------
    def eval_cases_replace(self, suite, cases) -> None:
        with self._tx() as c:
            c.execute("DELETE FROM eval_cases WHERE suite=%s", (suite,))
            for item in cases:
                c.execute(
                    "INSERT INTO eval_cases(suite, question, gold_answer,"
                    " gold_citations, expect_refusal, tags)"
                    " VALUES(%s,%s,%s,%s,%s,%s)",
                    (suite, item["question"], item.get("gold_answer", ""),
                     dumps(item.get("gold_citations", [])),
                     1 if item.get("expect_refusal") else 0,
                     dumps(item.get("tags", []))),
                )

    def eval_cases_get(self, suite):
        with self._tx() as c:
            rows = [dict(r) for r in c.execute(
                "SELECT * FROM eval_cases WHERE suite=%s ORDER BY id", (suite,)).fetchall()]
        for r in rows:
            r["gold_citations"] = loads(r["gold_citations"], [])
            r["tags"] = loads(r["tags"], [])
        return rows

    def eval_run_save(self, suite, total, passed, metrics_json, gates_json,
                      gate_passed, details_json) -> int:
        with self._tx() as c:
            cur = c.execute(
                "INSERT INTO eval_runs(ts, suite, total, passed, metrics, gates,"
                " gate_passed, details) VALUES(%s,%s,%s,%s,%s,%s,%s,%s) RETURNING id",
                (now_iso(), suite, total, passed, metrics_json, gates_json,
                 gate_passed, details_json),
            )
            return cur.fetchone()["id"]

    def eval_runs_list(self, suite="", limit=20):
        with self._tx() as c:
            if suite:
                return [dict(r) for r in c.execute(
                    "SELECT id, ts, suite, total, passed, metrics, gates, gate_passed"
                    " FROM eval_runs WHERE suite=%s ORDER BY id DESC LIMIT %s",
                    (suite, limit)).fetchall()]
            return [dict(r) for r in c.execute(
                "SELECT id, ts, suite, total, passed, metrics, gates, gate_passed"
                " FROM eval_runs ORDER BY id DESC LIMIT %s", (limit,)).fetchall()]

    def eval_run_get(self, run_id):
        with self._tx() as c:
            rows = [dict(r) for r in c.execute(
                "SELECT * FROM eval_runs WHERE id=%s", (run_id,)).fetchall()]
        return rows[0] if rows else None

    # ---------- 安全审计域 ----------
    def audit_log(self, user_id, action, tool, params, decision, reason) -> None:
        from .obs.tracing import get_trace_id

        with self._tx() as c:
            c.execute(
                "INSERT INTO audit_logs(ts, user_id, trace_id, action, tool, params,"
                " decision, reason) VALUES(%s,%s,%s,%s,%s,%s,%s,%s)",
                (now_iso(), user_id, get_trace_id(), action, tool, params, decision,
                 reason),
            )

    def audit_list(self, limit=100, decision=""):
        with self._tx() as c:
            if decision:
                return [dict(r) for r in c.execute(
                    "SELECT * FROM audit_logs WHERE decision=%s"
                    " ORDER BY id DESC LIMIT %s", (decision, limit)).fetchall()]
            return [dict(r) for r in c.execute(
                "SELECT * FROM audit_logs ORDER BY id DESC LIMIT %s", (limit,)).fetchall()]

    def injection_hit(self, user_id, source, snippet, patterns, score, blocked) -> None:
        with self._tx() as c:
            c.execute(
                "INSERT INTO injection_hits(ts, user_id, source, snippet, patterns,"
                " score, blocked) VALUES(%s,%s,%s,%s,%s,%s,%s)",
                (now_iso(), user_id, source, snippet[:200], patterns, score, blocked),
            )

    def injection_list(self, limit=100):
        with self._tx() as c:
            return [dict(r) for r in c.execute(
                "SELECT * FROM injection_hits ORDER BY id DESC LIMIT %s",
                (limit,)).fetchall()]


_pg: PgRepository | None = None
_pg_lock = threading.Lock()


def get_pg() -> PgRepository:
    global _pg
    if _pg is None:
        with _pg_lock:
            if _pg is None:
                _pg = PgRepository(settings.pg_dsn)
                _pg.init_schema()
    return _pg


# 业务域方法一览（HybridStore 路由依据；与 PgRepository 方法集对齐）
PG_DOMAIN_METHODS = {
    "kv_get", "kv_set",
    "create_user", "get_user_by_username", "get_user", "list_users",
    "get_profile", "upsert_profile",
    "create_session", "touch_session", "get_session", "list_sessions",
    "delete_session", "add_message", "get_messages",
    "mem_short_get", "mem_short_set", "mem_long_get", "mem_long_set",
    "library_upsert", "library_list",
    "auth_token_save", "auth_token_get_valid", "auth_token_revoke",
    "auth_token_revoke_all",
    "create_order", "get_order", "set_order_status", "count_recent_orders",
    "strategy_get", "strategy_set", "strategy_all",
    "campaign_create", "campaign_update", "campaign_delete", "campaign_list",
    "campaigns_active",
    "priority_upsert", "priority_list", "priority_delete",
    "exp_create", "exp_list", "exp_get_by_name", "exp_get", "exp_finish",
    "exp_assign", "exp_get_assignment",
    "prompt_latest", "prompt_save",
    "event_enqueue", "event_claim_batch", "event_mark_done", "event_release",
    "event_insert", "events_query", "events_count",
    "feature_user_upsert", "feature_user_map", "feature_book_upsert",
    "feature_book_map",
    "rec_model_save", "rec_model_latest", "rec_candidates_save",
    "rec_candidates_get",
    "mh_call_log", "mh_quota_incr", "mh_quota_get", "mh_stats_by_model",
    "mh_recent_calls",
    "eval_cases_replace", "eval_cases_get", "eval_run_save", "eval_runs_list",
    "eval_run_get",
    "audit_log", "audit_list", "injection_hit", "injection_list",
}
